### ISSUE TITLE
Typo slide 7 lecture 5

### ISSUE THREAD

**Issue by quinoba** [MansMeg/BSDA#4]
I believe there is a typo in slide 7 lecture 5 in the expression:

$$
\text{where} \quad
\begin{aligned}
\theta_{j,t-1} = & (\theta_{1,J},\dots,\theta_{j-1,t},
        \theta_{j+1,t-1},\dots,\theta_{t-1,J})
\end{aligned}
$$

I think the right expression should be:

$$
\text{where} \quad
\begin{aligned}
\theta_{-j,t-1} = & (\theta_{1,t},\dots,\theta_{j-1,t},
        \theta_{j+1,t-1},\dots,\theta_{J,t-1})
\end{aligned}
$$

Or probably I am missing something, but I couldn't make sense of the first expression.

**Comment by MansMeg** [comment]
Yes indeed! Do you want to do a PR and fix the typo? Or should I just do it?

**Comment by MansMeg** [comment]
This is fixed now. Thanks!
