### ISSUE TITLE
Don't recommend 'monitor' function

### ISSUE THREAD

**Issue by ninpnin** [MansMeg/BSDA#6]
Apparently, the 'monitor' that we recommend (Assignment 6) is not really working as it should. It doesn't respond to the number of warmup steps.

Here's a GH issue from three years ago where a Stan dev recommends against it: https://github.com/stan-dev/rstan/issues/759

If this is still the case I think we shouldn't recommend that function to students.

**Comment by MansMeg** [comment]
Great! Yes, I dont use it myself. Can you do a Pr to fix this?

**Comment by ninpnin** [comment]
What should we recommend instead? Or should we just remove the hint?

**Comment by MansMeg** [comment]
What is it used for, traceplots and Rhats and the like? I don't remember.

**Comment by ninpnin** [comment]
The assignment seems to ask the students for $\hat R$ only:

<img width="786" alt="Screenshot 2023-10-10 at 13 03 37" src="https://github.com/MansMeg/BSDA/assets/10169469/0f630caf-e4de-4805-9196-021c40966bce">

Then we maybe just remove the recommendation, or alternatively add that you can get the samples for _Rhat_ with the _extract_ function.

**Comment by MansMeg** [comment]
Yes. I can fix this.

**Comment by MansMeg** [comment]
Fixed in e9681c0
